<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $clothes = Category::create(['name_ar' => 'ملابس',  'name_en' => 'Clothes',         'name_ur' => 'کپڑے',        'slug' => 'Clothes',     'cover' => 'images/category/clothes.jpg',           'status' => true,  'parent_id' => null,          "description_ar" => "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة .", 'description_en' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'description_ur' => 'یہ متن متن کی ایک مثال ہے جسے ایک ہی جگہ میں تبدیل کیا جا سکتا ہے۔']);
        Category::create(['name_ar' => 'ملابس حريمي 1',     'name_en' => 'Women T-shirt',   'name_ur' => 'خواتین کی ٹی شرٹ',       'slug' => 'Women-T-shirt',     'cover' => 'images/category/womenclothes.jpg',      'status' => true, 'parent_id' => $clothes->id , "description_ar" => "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة .", 'description_en' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'description_ur' => 'یہ متن متن کی ایک مثال ہے جسے ایک ہی جگہ میں تبدیل کیا جا سکتا ہے۔']);
        Category::create(['name_ar' => 'ملابس حريمي 2',     'name_en' => 'Women2 T-shirt',  'name_ur' => 'خواتین2 ٹی شرٹ',      'slug' => 'Women2-T-shirt',     'cover' => 'images/category/womenclothes2.jpg',     'status' => true, 'parent_id' => $clothes->id , "description_ar" => "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة .", 'description_en' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'description_ur' => 'یہ متن متن کی ایک مثال ہے جسے ایک ہی جگہ میں تبدیل کیا جا سکتا ہے۔']);
        Category::create(['name_ar' => 'ملابس رجالي 1',     'name_en' => 'man T-shirt',     'name_ur' => 'آدمی کی ٹی شرٹ',         'slug' => 'man-T-shirt',     'cover' => 'images/category/manclothes.jpg',        'status' =>true,  'parent_id' => $clothes->id , "description_ar" => "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة .", 'description_en' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'description_ur' => 'یہ متن متن کی ایک مثال ہے جسے ایک ہی جگہ میں تبدیل کیا جا سکتا ہے۔']);
        Category::create(['name_ar' => 'ملابس رجالي 2',     'name_en' => 'man2 T-shirt',    'name_ur' => 'مین 2 ٹی شرٹ',        'slug' => 'man2-T-shirt',     'cover' => 'images/category/manclothes2.jpg',       'status' => true, 'parent_id' => $clothes->id , "description_ar" => "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة .", 'description_en' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'description_ur' => 'یہ متن متن کی ایک مثال ہے جسے ایک ہی جگہ میں تبدیل کیا جا سکتا ہے۔']);


        $shoes = Category::create(['name_ar' => 'أحذية',    'name_en' => 'shoes',         'name_ur' => 'جوتے',             'slug' => 'shoes',     'cover' => 'images/category/shoes.jpg',           'status' => true,  'parent_id' => null,          "description_ar" => "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة .", 'description_en' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'description_ur' => 'یہ متن متن کی ایک مثال ہے جسے ایک ہی جگہ میں تبدیل کیا جا سکتا ہے۔']);
        Category::create(['name_ar' => 'أحذية حريمي 1',     'name_en' => 'Women shoes',   'name_ur' => 'خواتین کے جوتے',       'slug' => 'Women-shoes',     'cover' => 'images/category/womenshoes.jpg',      'status' => true, 'parent_id' => $shoes->id , "description_ar" => "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة .", 'description_en' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'description_ur' => 'یہ متن متن کی ایک مثال ہے جسے ایک ہی جگہ میں تبدیل کیا جا سکتا ہے۔']);
        Category::create(['name_ar' => 'أحذية حريمي 2',     'name_en' => 'Women2 shoes',  'name_ur' => 'خواتین2 جوتے',      'slug' => 'Women2-shoes',     'cover' => 'images/category/womenshoes2.jpg',     'status' => true, 'parent_id' => $shoes->id , "description_ar" => "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة .", 'description_en' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'description_ur' => 'یہ متن متن کی ایک مثال ہے جسے ایک ہی جگہ میں تبدیل کیا جا سکتا ہے۔']);
        Category::create(['name_ar' => 'أحذية رجالي 1',     'name_en' => 'man shoes',     'name_ur' => 'آدمی کے جوتے',         'slug' => 'man-shoes',     'cover' => 'images/category/manshoes.jpg',        'status' =>true,  'parent_id' => $shoes->id , "description_ar" => "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة .", 'description_en' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'description_ur' => 'یہ متن متن کی ایک مثال ہے جسے ایک ہی جگہ میں تبدیل کیا جا سکتا ہے۔']);
        Category::create(['name_ar' => 'أحذية رجالي 2',     'name_en' => 'man2 shoes',    'name_ur' => 'آدمی 2 جوتے',        'slug' => 'man2-shoes',     'cover' => 'images/category/manshoes2.jpg',       'status' => true, 'parent_id' => $shoes->id , "description_ar" => "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة .", 'description_en' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'description_ur' => 'یہ متن متن کی ایک مثال ہے جسے ایک ہی جگہ میں تبدیل کیا جا سکتا ہے۔']);


        $watches = Category::create(['name_ar' => 'ساعات',  'name_en' => 'watches',         'name_ur' => 'گھڑیاں',             'slug' => 'watches',     'cover' => 'images/category/watches.jpg',           'status' => true,  'parent_id' => null,          "description_ar" => "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة .", 'description_en' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'description_ur' => 'یہ متن متن کی ایک مثال ہے جسے ایک ہی جگہ میں تبدیل کیا جا سکتا ہے۔']);
        Category::create(['name_ar' => 'ساعات حريمي 1',     'name_en' => 'Women watches',   'name_ur' => 'خواتین کی گھڑیاں',       'slug' => 'Women-watches',     'cover' => 'images/category/womenwatches.jpg',      'status' => true, 'parent_id' => $watches->id , "description_ar" => "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة .", 'description_en' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'description_ur' => 'یہ متن متن کی ایک مثال ہے جسے ایک ہی جگہ میں تبدیل کیا جا سکتا ہے۔']);
        Category::create(['name_ar' => 'ساعات حريمي 2',     'name_en' => 'Women2 watches',  'name_ur' => 'خواتین 2 گھڑیاں',      'slug' => 'Women2-watches',     'cover' => 'images/category/womenwatches2.jpg',     'status' => true, 'parent_id' => $watches->id , "description_ar" => "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة .", 'description_en' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'description_ur' => 'یہ متن متن کی ایک مثال ہے جسے ایک ہی جگہ میں تبدیل کیا جا سکتا ہے۔']);
        Category::create(['name_ar' => 'ساعات رجالي 1',     'name_en' => 'man watches',     'name_ur' => 'آدمی دیکھتا ہے',         'slug' => 'man-watches',     'cover' => 'images/category/manwatches.jpg',        'status' =>true,  'parent_id' => $watches->id , "description_ar" => "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة .", 'description_en' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'description_ur' => 'یہ متن متن کی ایک مثال ہے جسے ایک ہی جگہ میں تبدیل کیا جا سکتا ہے۔']);
        Category::create(['name_ar' => 'ساعات رجالي 2',     'name_en' => 'man2 watches',    'name_ur' => 'آدمی 2 گھڑیاں',        'slug' => 'man2-watches',     'cover' => 'images/category/manwatches2.jpg',       'status' => true, 'parent_id' => $watches->id , "description_ar" => "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة .", 'description_en' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'description_ur' => 'یہ متن متن کی ایک مثال ہے جسے ایک ہی جگہ میں تبدیل کیا جا سکتا ہے۔']);

        $electronics = Category::create(['name_ar' => 'أدوات',    'name_en' => 'electronics',         'name_ur' => 'الیکٹرانکس',             'slug' => 'electronics',     'cover' => 'images/category/electronics.jpg',           'status' => true,  'parent_id' => null,          "description_ar" => "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة .", 'description_en' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'description_ur' => 'یہ متن متن کی ایک مثال ہے جسے ایک ہی جگہ میں تبدیل کیا جا سکتا ہے۔']);
        Category::create(['name_ar' => 'أدوات حريمي 1',     'name_en' => 'Women electronics',   'name_ur' => 'خواتین الیکٹرانکس',       'slug' => 'Women-electronics',     'cover' => 'images/category/womenelectronics.jpg',      'status' => true, 'parent_id' => $electronics->id , "description_ar" => "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة .", 'description_en' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'description_ur' => 'یہ متن متن کی ایک مثال ہے جسے ایک ہی جگہ میں تبدیل کیا جا سکتا ہے۔']);
        Category::create(['name_ar' => 'أدوات حريمي 2',     'name_en' => 'Women2 electronics',  'name_ur' => 'خواتین 2 الیکٹرانکس',      'slug' => 'Women2-electronics',     'cover' => 'images/category/womenelectronics2.jpg',     'status' => true, 'parent_id' => $electronics->id , "description_ar" => "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة .", 'description_en' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'description_ur' => 'یہ متن متن کی ایک مثال ہے جسے ایک ہی جگہ میں تبدیل کیا جا سکتا ہے۔']);
        Category::create(['name_ar' => 'أدوات رجالي 1',     'name_en' => 'man electronics',     'name_ur' => 'آدمی الیکٹرانکس',         'slug' => 'man-electronics',     'cover' => 'images/category/manelectronics.jpg',        'status' =>true,  'parent_id' => $electronics->id , "description_ar" => "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة .", 'description_en' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'description_ur' => 'یہ متن متن کی ایک مثال ہے جسے ایک ہی جگہ میں تبدیل کیا جا سکتا ہے۔']);
        Category::create(['name_ar' => 'أدوات رجالي 2',     'name_en' => 'man2 electronics',    'name_ur' => 'مین 2 الیکٹرانکس',        'slug' => 'man2-electronics',     'cover' => 'images/category/manelectronics2.jpg',       'status' => true, 'parent_id' => $electronics->id , "description_ar" => "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة .", 'description_en' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'description_ur' => 'یہ متن متن کی ایک مثال ہے جسے ایک ہی جگہ میں تبدیل کیا جا سکتا ہے۔']);

    }
}
